const alpfabet = [
  { name: "A", value: "A", visible: true },
  { name: "B", value: "B", visible: true },
  { name: "C", value: "C", visible: true },
  { name: "D", value: "D", visible: true },
  { name: "E", value: "E", visible: true },
  { name: "F", value: "F", visible: true },
  { name: "G", value: "G", visible: true },
  { name: "H", value: "H", visible: true },
  { name: "I", value: "I", visible: true },
  { name: "J", value: "J", visible: true },
  { name: "K", value: "K", visible: true },
  { name: "L", value: "L", visible: true },
  { name: "M", value: "M", visible: true },
  { name: "N", value: "N", visible: true },
  { name: "O", value: "O", visible: true },
  { name: "P", value: "P", visible: true },
  { name: "Q", value: "Q", visible: true },
  { name: "R", value: "R", visible: true },
  { name: "S", value: "S", visible: true },
  { name: "T", value: "T", visible: true },
  { name: "U", value: "U", visible: true },
  { name: "V", value: "V", visible: true },
  { name: "W", value: "W", visible: true },
  { name: "X", value: "X", visible: true },
  { name: "Y", value: "Y", visible: true },
  { name: "Z", value: "Z", visible: true },
];

export { alpfabet };
