const alpfabet = [
  { name: "A", value: "A", matched: false },
  { name: "B", value: "B", matched: false },
  { name: "C", value: "C", matched: false },
  { name: "D", value: "D", matched: false },
  { name: "E", value: "E", matched: false },
  { name: "F", value: "F", matched: false },
  { name: "G", value: "G", matched: false },
  { name: "H", value: "H", matched: false },
  { name: "I", value: "I", matched: false },
  { name: "J", value: "J", matched: false },
  { name: "K", value: "K", matched: false },
  { name: "L", value: "L", matched: false },
  { name: "M", value: "M", matched: false },
  { name: "N", value: "N", matched: false },
  { name: "O", value: "O", matched: false },
  { name: "P", value: "P", matched: false },
  { name: "R", value: "R", matched: false },
  { name: "S", value: "S", matched: false },
  { name: "T", value: "T", matched: false },
  { name: "U", value: "U", matched: false },
  { name: "V", value: "V", matched: false },
  { name: "W", value: "W", matched: false },
  { name: "X", value: "X", matched: false },
  { name: "Z", value: "Z", matched: false },
  { name: "Y", value: "Y", matched: false },
];

export { alpfabet };
