const words8 = [
  { value: "Felicidad", tip: "Alegría" },
  { value: "Pintores", tip: "Artistas" },
  { value: "Silencio", tip: "Quietud" },
  { value: "Serpiente", tip: "Reptil" },
  { value: "Florista", tip: "Florería" },
  { value: "Camarero", tip: "Mesero" },
  { value: "Palabras", tip: "Lenguaje" },
  { value: "Perfumes", tip: "Fragancias" },
  { value: "Elevador", tip: "Ascensor" },
  { value: "Maletin", tip: "Portafolio" },
  { value: "Futbol", tip: "Deporte" },
  { value: "Secretos", tip: "Confidencias" },
  { value: "Maquinas", tip: "Aparatos" },
  { value: "Examen", tip: "Prueba" },
  { value: "Precioso", tip: "Hermoso" },
  { value: "Torrente", tip: "Riachuelo" },
  { value: "Elefante", tip: "Animal" },
  { value: "Politica", tip: "Gobierno" },
  { value: "Adhesivo", tip: "Pegamento" },
  { value: "Anzuelo", tip: "Cebo" },
  { value: "Atletas", tip: "Deportistas" },
  { value: "Busqueda", tip: "Investigación" },
  { value: "Crucigrama", tip: "Rompecabezas" },
  { value: "Misterio", tip: "Enigma" },
  { value: "Vivienda", tip: "Hogar" },
  { value: "Velocidad", tip: "Rapidez" },
  { value: "Telescopio", tip: "Instrumento" },
  { value: "Escondite", tip: "Juego" },
  { value: "Biblioteca", tip: "Libros" },
];
export { words8 };
